[build]
  command = "yarn prod"
  publish = "dist"


[[redirects]]
  from = "/rss"
  to = "/rss.xml"
  status = 200


[[redirects]]
  from = "/ghost/"
  to = "https://cms.1900.live/ghost/"
  status = 301
  force = true

[[redirects]]
  from = "/*/edit"
  to = "https://cms.1900.live/:splat/edit"
  status = 301
  force = true

[[redirects]]
  from = "/.well-known/webfinger/*"
  to = "https://gts.1900.live/.well-known/webfinger"
  status = 301

[[redirects]]
  from = "/.well-known/host-meta/*"
  to = "https://gts.1900.live/.well-known/host-meta"
  status = 301

[[redirects]]
  from = "/.well-known/nodeinfo/*"
  to = "https://gts.1900.live/.well-known/nodeinfo"
  status = 301














[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
